# Generated by Django 4.2.3 on 2023-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('slug', models.CharField(max_length=40, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='photos/blog/', verbose_name='изображение')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('publication_attribute', models.BooleanField(verbose_name='признак публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='число просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(upload_to='photos/', verbose_name='изображение'),
        ),
    ]
